### ISSUE TITLE
No weapons in puddle jumper

### ISSUE THREAD

**Issue by ghost** [williamdefly/Evolutionaddonpack#49]
Unlike the CAP version, the puddle jumper in EAP does not seem to include the internal missiles activated when 'q' is pressed.

**Comment by Elanis** [comment]
Hi, 
Since we add the new keyboard system, all ships controls were merged to be used by one only keyboard. Then, the key to open the weapons isn't the same as in the CAP.
You Can view/change this key in the keyboard settings in the tools tabs.
I hope i helped you.

Elanis

**Comment by Elanis** [comment]
Is the bug still exists or you used the wrong key ?

If it's a bug, i'll check it.

**Comment by ghost** [comment]
Thankyou for alerting me to the alternate settings tool, I was able to get it working perfectly.

**Comment by Elanis** [comment]
You're welcome ;) I think adding some help overlays on the add-on.
