### ISSUE TITLE
ZPM and tampered ZPM error

### ISSUE THREAD

**Issue by pas341** [williamdefly/Evolutionaddonpack#88]
in [lua/entities/zpmmk3.lua](lua/entities/zpmmk3.lua) on line 85 you need to change from` local entities = Lib.RD.GetEntListTable(self); to local entities = Lib.GetEntListTable(self);` and in [lua/entities/tamperedzpm.lua](lua/entities/tamperedzpm.lua) on line 98 you need to do the same fix for the current version off spacebuild else the zpm wil not work when placed

**Comment by Elanis** [comment]
Yep, i made a mistake while importing from CAP in the Libraries ^^ Thanks for the report 👍
